site_name: Poetry PyCharm Plugin
site_description: A JetBrains PyCharm plugin for poetry.

theme:
    name: 'material'
    palette:
      primary: 'light blue'
      accent: 'light blue'
    analytics:
      gtag: 275257853
markdown_extensions:
  - codehilite
  - admonition
  - toc:
      permalink: 🔗

repo_name: koxudaxi/poetry-pycharm-plugin
repo_url: https://github.com/koxudaxi/poetry-pycharm-plugin
site_url: https://koxudaxi.github.io/poetry-pycharm-plugin

nav:
    - Overview: index.md
    - Install: install.md
    - Development: development.md
    - Changelog: changelog.md

plugins:
  - search